### PR TITLE
(hopefully) Fixed performance problem

### PR DESCRIPTION
**Pull request by LeanderK**
Assuming you used this https://github.com/sstrickx/yahoofinance-api library there is a new version available.

Instead of request every stock individually, a batch-request is now performed.

Running some simple tests showed significant performance improvements.

without batch request: 3, 4, 3, 4 Seconds elapsed calling the provideResource-method.
with batch request call i performed was under one second.

I haven't tested it on the rpi yet, maybe you can measure the performance gain and determine if we have to do some further optimizations.

### CODE REVIEW

**Comment by LeanderK** [comment]
btw as you can see in the unit test i used the following stocks to measure performance:
Google,GOOG
Apple,AAPL
Euro_to_dollar,EURUSD=X
Intel,INTC
Dow Jones Industrial Average,DJI
BMW,BMW.DE
Facebook,FB

**Comment by jundl77** [comment]
Ok I will test

**Comment by LeanderK** [comment]
Results?

**Comment by LeanderK** [comment]
if you can confirm similar results on the rpi i can delete my fork

**Comment by jundl77** [comment]
Im working on the sound right now, I will test everything later tonight

**Comment by jundl77** [comment]
on the raspberry pi, there is still a 20 sec delay

**Comment by jundl77** [comment]
On my computer however it is also instantly there - so it seems to be the raspberry pi, something that is also occurring with the TTS in combination with izousound, yet it is not that bad since it is contained in its own TTS thread (not the main thread)

**Pull request merged**
